# Main BetterLife Configuration File

# SQL settings
sql:
  enabled: false
  username: betterlife
  password: betterlife123
  database: minecraft
  prefix: betterlife_

events:
  # Is crop trample enabled globally?
  croptrample: true

# What is the default particle for new players?
defaultParticle: NOTE

# Zone Protection / Anti Grief
zoneprotection:

  # Is it enabled?
  enabled: true

  # What is the item to use for claiming/protecting?
  item: GOLDEN_SHOVEL

  # What world is it enabled in?
  worlds:
    - world

  # What is the cost per block?
  cost: 25.0
