# Main BetterLife Configuration File
events:
  # Whether crop trample protection is enabled or not. Default: true
  croptrample: true

# Set the default particle effect given when players first join the server. Default: NOTE
defaultParticle: NOTE