main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: '0.2'
description: "Basic server Essentials for the outgoing server owner"
author: GT3CH1
authors: [Starmism]
api-version: '1.13'
commands:
    bl:
        description: The primary command for BetterLife
        usage: "Usage: /bl [args]"
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: "Usage: /toggledownfall"
        permission: betterlife.toggledownfall
    roadboost:
        description: Toggles if you get speed 1 when you are over a defined road.
        usage: "Usage: /roadboost"
        permission: betterlife.roadboost
    trail:
        description: Sets a fancy trail behind your player
        usage: "Usage: /trail [list|help|set|add|rm]"
        permission: betterlife.trail
