main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: '0.2'
description: "Making running a Minecraft server a little more humane."
author: GT3CH1
authors: [Starmism]
api-version: '1.13'
commands:
    bl:
        description: The primary command for BetterLife
        usage: "Usage: /bl [args]"
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: "Usage: /toggledownfall"
        permission: betterlife.toggledownfall
    roadboost:
        description: Toggles if you get speed 1 when you are over a defined road.
        usage: "Usage: /roadboost"
        permission: betterlife.roadboost
    trail:
        description: Sets a fancy trail behind your player
        usage: "Usage: /trail [ list | help | set ]"
        permission: betterlife.trail
permissions:
    betterlife.trail.set:
        description: Allows the trail to be set per-player
        default: op
    betterlife.trail.toggle:
        description: Allows toggling of the trail.
        default: op
    betterlife.trail.particle.*:
        description: Allows access to every trail particle.
        default: op
    betterlife.toggledownfall:
        description: Toggles the weather
        default: op
    betterlife.roadboost:
        description: Gain a speed 1 boost over paths.
        default: op
    betterlife.reload:
        description: Reloads the configuration files of betterlife
        default: op
    