main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: 0.1
api-version: 1.13
commands:
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: |
                /toggledownfall
    croptrample:
        description: turns on or off crop trampling.
        usage: |
                /croptrample
    roadboost:
        description: Gives you speed 1 when you are over a defined road.
        usage: |
            /roadboost