main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: '0.1'
api-version: '1.13'
commands:
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: "Usage: /toggledownfall"
        permission: betterlife.command.toggledownfall
    croptrample:
        description: Toggles off crop trampling.
        usage: "Usage: /croptrample"
        permission: betterlife.command.croptrample
    roadboost:
        description: Toggles if you get speed 1 when you are over a defined road.
        usage: "Usage: /roadboost"
        permission: betterlife.command.roadboost
    trail:
        description: Sets a fancy trail behind your player
        usage: "Usage: /trail [list|help|set|add|rm]"
        permission: betterlife.command.trail