main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: 0.1
api-version: 1.13
commands:
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: |
                /toggledownfall
        permission: betterlife.command.toggledownfall
    croptrample:
        description: Toggles off crop trampling.
        usage: |
                /croptrample
        permission: betterlife.command.toggledownfall
    roadboost:
    	description: Toggles if you get speed 1 when you are over a defined road.
    	usage: |
    			/roadboost
		permission: betterlife.command.roadboost
    trail:
        description: Sets a fancy trail behind your player
        usage: |
            /trail
        permission: betterlife.command.trail