# Main BetterLife Configuration File

# SQL Database Connection
# dbType: The type of database you're using. Must be: mysql or mariadb
# host: IP to connect to
# database: The name of the schema to use
# username: Username of user. Recommended to create one specifically for Minecraft
# password: Password of user. ^^
sql:
  dbType: mysql
  host: localhost
  database: BetterLife
  username: username
  password: password

events:
  # Enable Crop Trample Protection
  croptrample: true

# Default particle (must be in all caps)
# Default: NOTE
defaultParticle: NOTE

# Number of homes allowed per player
# Bypass this with the betterlife.homes.bypass permission
homes: 2

# How many seconds to countdown before teleporting a player home
home-countdown: 5

# ZoneSafe - Allows players to protect zones
zonesafe:
  enabled: true
  # The item to use for claiming zones
  item: GOLDEN_SHOVEL
  # List of worlds to allow zone claiming in
  worlds:
    - world

  # Cost per block claimed
  cost: 25.0
