main: me.gt3ch1.betterlife.Main.Main
name: BetterLife
version: '0.5'
description: "Making running a Minecraft server a little more humane."
authors: [Starmism, GT3CH1]
api-version: '1.13'
softdepend: [Vault]
commands:
    bl:
        description: The primary command for BetterLife
        usage: "Usage: /bl [args]"
    eco:
        description: Various economy-related commands
        usage: "Usage: /eco [ bal ]"
        permission: betterlife.eco
    home:
        description: Allows users to go home!
        usage: "Usage: /home [ home ] or /home [ set / del ] [ home ]"
        permission: betterlife.home
    mute:
        description: Mutes a player
        usage: "Usage: /mute [ player ]"
        permission: betterlife.mute
    roadboost:
        description: Toggles if you get speed 1 when you are over a defined road.
        usage: "Usage: /roadboost"
        permission: betterlife.roadboost
    teleport:
        description: Teleports a player to another player.
        usage: "Usage: /teleport [player one] [player two]"
        permission: betterlife.teleport
    toggledownfall:
        description: Toggles whether or not it is storming
        usage: "Usage: /toggledownfall"
        permission: betterlife.toggledownfall
    trail:
        description: Sets a fancy trail behind your player
        usage: "Usage: /trail [ list | help | set ]"
        permission: betterlife.trail
    setspawn:
        description: Sets a the games spawnpoint to your location.
        usage: "Usage: /setspawn"
        permission: betterlife.setspawn
    spawn:
        description: Teleport to the game's spawn point.
        usage: "Usage: /spawn [ set ]"
        permission: betterlife.spawn
    unmute:
        description: Unmutes a player
        usage: "Usage: /unmute [ player ]"
        permission: betterlife.unmute
    warp:
        description: Teleports a player to a warp!
        usage: "Usage: /warp <set, list, del> [ location ]"
        permission: betterlife.warp
permissions:
    betterlife.eco.bal:
        description: Allows player to see their current balance
    betterlife.eco.bal.others:
        description: Allows player to see other players' current balance
        default: op
    betterlife.home:
        description: Allows player to go home
        default: op
    betterlife.home.set:
        description: Allows player to go home, delete a home, and list homes.
        default: op
    betterlife.home.list.others:
        description: Allows player to list others homes.
        default: op
    betterlife.home.*:
        description: All betterlife home commands
        default: op
    betterlife.mute:
        description: Allows muting of players.
        default: op
    betterlife.mute.bypass:
        description: Bypasses muting.
        default: op
    betterlife.roadboost:
        description: Gain a speed 1 boost over paths.
        default: op
    betterlife.teleport:
        description: Teleports a player.
        default: op
    betterlife.teleport.others:
        description: Teleports a player to other players.
        default: op
    betterlife.toggledownfall:
        description: Toggles the weather
        default: op
    betterlife.trail.set:
        description: Allows the trail to be set per-player
        default: op
    betterlife.trail.toggle:
        description: Allows toggling of the trail.
        default: op
    betterlife.trail.particle.*:
        description: Allows access to every trail particle.
        default: op
    betterlife.reload:
        description: Reloads the configuration files of betterlife
        default: op
    betterlife.spawn:
        description: Allows players to teleport to spawn
        default: op
    betterlife.setspawn:
        description: Allows a player to set the spawnpoint
        default: op
    betterlife.unmute:
        description: Allows unmuting of players.
        default: op
    betterlife.warp:
        description: Allows access to the /warp command
        default: op
    betterlife.warp.set:
        description: Sets a warp at the current location
        default: op
    betterlife.warp.del:
        description: Deletes a warp
        default: op
    betterlife.warp.list:
        description: Allows players to list warps
        default: op
    betterlife.warp.*:
        description: Allows access to all warps.
        default: op